### ISSUE TITLE
Delay on actual brightness change from keystroke

### ISSUE THREAD

**Issue by whatnameisit** [hieplpvip/AppleBacklightSmoother#5]
Hi, thanks for this kext and amazing AsusSMC.
When I press Fn+F7 [Turn on/off screen], on Asus X510UA (an S510 variant) the input is immediate, but the time it takes for the screen to actually turn on/off is noticeable. It's longer with the ABS kext than without.
I think it's because without the kext each in/decrement is 1 and with the kext 1/4 and the time to process each change is different. 18 levels vs. 72 levels..?
It takes about 2 seconds to completely turn on/off. Would you be interested to add a fix to make it change faster?
Thanks.

**Comment by hieplpvip** [comment]
I will fix it

**Comment by whatnameisit** [comment]
WhateverGreen 1.5.3
