### ISSUE TITLE
Display can’t be turned off completely by FN-F7

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/AppleBacklightSmoother#6]
Display can’t be turned off completely by lowering brightness or by pressing Asus’s FN+F7 key for «Turn off the display»

**Comment by hieplpvip** [comment]
The brightness duty cycle should be correctly set to 0. This is not caused by AppleBacklightSmoother.

It seems to be a hardware bug (I have this too).

**Comment by kasti0** [comment]
i have the same problem and without AppleBacklightSmoother the backlight turns completely off. so most likely not a hardware bug. the kext introduces a new "Backlight" attribute for the display instead of the attribute "bklt" that´s already provided
