### ISSUE TITLE
Display does not turn completely black on lowest brightness-setting

### ISSUE THREAD

**Issue by benbender** [hieplpvip/AppleBacklightSmoother#8]
Hey,

I just noticed that the display of my Thinkpad T480, KabyLake-R, iGPU-pciId 5918, doesnt turn completely black on lowest brightness-setting as it normally would. Would be nice to get it fixed as I'm often turning my screen down to listen to podcasts :)

Thanks again for your work!

Best

**Comment by Ubsefor** [comment]
Duplicate of #6
