### ISSUE TITLE
Lower Max Brightness after using AppleBacklightSmoother kext

### ISSUE THREAD

**Issue by xenonstride** [hieplpvip/AppleBacklightSmoother#9]
When the kext is used the max brightness is reduced. Without the kext the max brightness is more.

Please, can you fix it? I have Lenovo IdeaPad S340 with i5-1035G1 (Ice Lake)

**Comment by joske** [comment]
Same problem on Dell XPS 13 9370. I set the max to 0xffff. When I set brightness to minimum and crank it up, I can notice that about halfway it jumps back to lower brightness before increasing again.
